accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
]

microlly/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('microlly_blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

microlly_blog/urls.py
from django.urls import path

from microlly_blog import views

app_name = 'microlly_blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='create'),
    path('post_by/<str:author>', views.list_post_user, name='list_post_user'),
    path('delete/<slug:slug>/<int:pk>', views.post_delete, name='delete'),
    path('post/<slug:slug>/<int:pk>', views.post_details, name='details'),
    path('edit/<slug:slug>/<int:pk>', views.post_edit, name='edit'),
]

accounts/models.py
from django.db import models

# Create your models here.

microlly_blog/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()
    slug = models.SlugField(default='a-slug')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    release_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def preview(self):
        return self.body[:50]+'...'

    def unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        self.slug = self.unique_slug()
        super().save(*args, **kwargs)

    class Meta():
        verbose_name = 'Publication'
        verbose_name_plural = 'Publications'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    forename = forms.CharField(max_length=30, required=False, help_text='Optional./Optionnel.')
    surname = forms.CharField(max_length=30, required=False, help_text='Optional./Optionnel.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address./Requis. Veuillez saisir une addresse e-mail valide.')

    class Meta:
        model = User
        fields = ('username', 'forename', 'surname',
                  'email', 'password1', 'password2',)

microlly_blog/forms.py
from django import forms
from microlly_blog import models


class PostCreate(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body']


class PostEdit(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from accounts import forms


# Create your views here.


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST: 
                return redirect(request.POST.get('next'))
            else: #Renvoie sur la page d'acceuil
                return redirect('microlly_blog:index')
    else:  #Renvoie sur la page de connexion
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('microlly_blog:index')
    else:
        return redirect('microlly_blog:index')

def signup_view(request):
    if request.method == 'POST':
        form = forms.SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('microlly_blog:index')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

microlly_blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from microlly_blog import forms
from microlly_blog.models import Post

# Create your views here.


def index(request):
    posts_list = Post.objects.all().order_by('-release_date')
    paginator = Paginator(posts_list, 9)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    return render(request, 'microlly_blog/index.html', {'latest_posts': posts})

@login_required(login_url="/accounts/login/")
def post_create(request):
    if request.method == 'POST':
        form = forms.PostCreate(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('microlly_blog:index')
    else:
        form = forms.PostCreate()
    return render(request, 'microlly_blog/post_create.html', {'form': form})

def post_details(request, slug, pk):
    post = get_object_or_404(Post, slug=slug, pk=pk)
    return render(request, 'microlly_blog/details.html', {'post': post})


@login_required(login_url="/accounts/login/")
def post_edit(request, slug, pk):
    post = get_object_or_404(Post, slug=slug, pk=pk)
    form = forms.PostEdit(request.POST or None, instance=post)
    if request.user != post.author:
        return redirect('microlly_blog:index')
    if request.method == 'POST':
        if form.is_valid():
            post.save()
            return redirect('microlly_blog:index')
    context = {
        "form": form,
        "post": post,
    }
    return render(request, 'microlly_blog/post_edit.html', context)

def list_post_user(request, author):                    # Affichage des posts
    author = get_object_or_404(User, username=author)   # Récupère l'auteur
    posts_list = Post.objects.filter(author=author)     # Récupère les posts
    paginator = Paginator(posts_list, 9)                # Mise en page
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    context = {
        "author": author,
        "list_posts_user": posts,
    }
    return render(request, 'microlly_blog/list_posts_user.html', context)

def post_delete(request, slug, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user != post.author:                 # Vérifie que auteur=utilisateur connecter sinon il peut pas le supprimer
        return redirect('microlly_blog:index')
    if request.method == 'POST':
        post.delete()
        return redirect('microlly_blog:index')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block section-title %}
Login
{% endblock %}

{% block content %}
<form class="d-flex flex-column" action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {% include 'form.html' with form=form %}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
    <input type="submit" class="btn btn-dark" value="Login">
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block section-title %}
Sign up
{% endblock %}



{% block content %}
<form class="d-flex flex-column" action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {% include 'form.html' with form=form %}
    <input type="submit" class="btn" value="Signup">
</form>
{% endblock %}

templates/base_layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <title>Microlly</title>
</head>

<body>
    <header>
            <div>
                 <div class="container text-center">
                     <h1>Microlly</h1>
                 </div>
             </div>
        <nav class="navbar navbar-expand-sm ">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">
                </span>
            </button>
            <div class="collapse navbar-collapse" id="navDropdown">
                <ul class="navbar-nav mx-4">
                    <li class="nav-item mx-1">
                        <form class="form-inline" action="{% url 'microlly_blog:index' %}" method="POST">
                            {% csrf_token %}
                            <button type="submit">HOME</button>
                        </form>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item mx-1">
                        <form class="form-inline" action="{% url 'microlly_blog:create' %}" method="POST">
                            {% csrf_token %}
                            <button type="submit">Création de publication</button>
                        </form>
                    </li>
                    <li class="nav-item mx-1">
                        <form class="form-inline" action="{% url 'accounts:logout' %}" method="POST">
                            {% csrf_token %}
                            <button type="submit">Déconnexion</button>
                        </form>
                    </li>
                    {% else %}
                    <li class="nav-item mx-1">
                        <form class="form-inline" action="{% url 'accounts:login' %}" method="POST">
                            {% csrf_token %}
                            <button  type="submit">Connexion</button>
                        </form>
                    </li>
                    <li class="nav-item mx-1">
                        <form class="form-inline" action="{% url 'accounts:signup' %}" method="POST">
                            {% csrf_token %}
                            <button type="submit">S'inscrire</button>
                        </form>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <section class="main-section">
        <div class="container">
            <br>
            {% block content %}
            {% endblock %}
        </div>
    </section>
</body>
</html>

templates/form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
{{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
    {{ error }}
    {% endfor %}
</div>
{% endif %}

{% for field in form.visible_fields %}
<div class="form-group">
    {{ field.label_tag }}
    {% if form.is_bound %}
        {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error }}
                </div>
            {% endfor %}
        {% else %}
            {% render_field field class="form-control is-valid" %}
        {% endif %}
    {% else %}
        {% render_field field class="form-control" %}
    {% endif %}
    {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
</div>
{% endfor %}